### ISSUE TITLE
[-] Missing required parameter 'digestmod'.

### ISSUE THREAD

**Issue by rockabillycat666** [Ridter/noPac#8]
Good afternoon, 

Everything was working properly yesterday.. today I got the following error:

```
─$ python3 noPac.py 'domain.local'/user:'password' -dc-ip 172.16.2.x -dc-host dc-hostname --impersonate administrator -dump -use-ldap -debug

███    ██  ██████  ██████   █████   ██████ 
████   ██ ██    ██ ██   ██ ██   ██ ██      
██ ██  ██ ██    ██ ██████  ███████ ██      
██  ██ ██ ██    ██ ██      ██   ██ ██      
██   ████  ██████  ██      ██   ██  ██████ 
                                           
                                        
    
[+] Impacket Library Installation Path: /home/kali/.local/lib/python3.9/site-packages/impacket
Traceback (most recent call last):
  File "/home/kali/Toys/noPac/noPac.py", line 385, in <module>
    samtheadmin(username, password, domain, options)
  File "/home/kali/Toys/noPac/noPac.py", line 95, in samtheadmin
    ldap_server, ldap_session = init_ldap_session(options, domain, username, password, lmhash, nthash)
  File "/home/kali/Toys/noPac/utils/helper.py", line 255, in init_ldap_session
    return init_ldap_connection(target, args.use_ldap, args, domain, username, password, lmhash, nthash)
  File "/home/kali/Toys/noPac/utils/helper.py", line 242, in init_ldap_connection
    ldap_session = ldap3.Connection(ldap_server, user=user, password=password, authentication=ldap3.NTLM, auto_bind=True)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 321, in __init__
    self.do_auto_bind()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 338, in do_auto_bind
    self.bind(read_server_info=True)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 563, in bind
    response = self.do_ntlm_bind(controls)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 1302, in do_ntlm_bind
    request = bind_operation(self.version, 'SICILY_RESPONSE_NTLM', ntlm_client, result['server_creds'])
  File "/usr/local/lib/python3.9/dist-packages/ldap3/operation/bind.py", line 81, in bind_operation
    server_creds = name.create_authenticate_message()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/ntlm.py", line 379, in create_authenticate_message
    nt_challenge_response = self.compute_nt_response()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/ntlm.py", line 485, in compute_nt_response
    response_key_nt = self.ntowf_v2()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/ntlm.py", line 497, in ntowf_v2
    return hmac.new(password_digest, (self.user_name.upper() + self.user_domain).encode('utf-16-le')).digest()
  File "/usr/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.9/hmac.py", line 56, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
[-] Missing required parameter 'digestmod'.



```

**Comment by rockabillycat666** [comment]
I updated everything that was installed with pip3... it works now.
